name: Deploy Discord Quiz Bot

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  RESOURCE_GROUP: discordQuizBotRG
  LOCATION: eastus  # Specify your preferred location
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  NODE_VERSION: '22.x'                      # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            dist/**
            lib/**

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./dist

      - name: Set up Bicep
        run: |
          az bicep install
          az bicep upgrade

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group
        run: |
          az group create --name $RESOURCE_GROUP --location $LOCATION

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file main.bicep \
            --parameters discordBotToken=$DISCORD_BOT_TOKEN

      - name: Deploy Function App code
        run: |
          az functionapp deployment source config-zip \
            --name ${functionAppName} \
            --resource-group $RESOURCE_GROUP \
            --src ./dist/deployment.zip
